site_name: Fabián Abarca

nav:
  - Inicio: index.md
  - Investigación: investigacion.md
  - Docencia: docencia.md
  - Acción Social: accionsocial.md
  - Biografía: personal.md

theme:
  name: material
  language: es
  palette:
    primary: black
  logo: /assets/img/fa_blanco.png
  favicon: /assets/img/favicon.png
  features:
    - navigation.expand
    - navigation.tabs
    - toc.integrate


repo_url: https://github.com/fabianabarca/puntocom
repo_name: fabianabarca/puntocom