site_name: Fabián Abarca

nav:
  - Inicio: index.md
  - Investigación: investigacion.md
  - Docencia: docencia.md
  - Acción Social: accionsocial.md
  - Biografía: personal.md

theme:
  name: material
  language: es
  palette:
    primary: blue grey
  logo: assets/img/fa_blanco.png
  favicon: assets/img/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
extra:
  social:
    - icon: fontawesome/brands/x-twitter 
      link: https://twitter.com/fabianabarca
    - icon: fontawesome/brands/github 
      link: https://github.com/fabianabarca
  generator: false
  analytics:
    provider: google
    property: G-PNHQXS2XGZ

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
